name: Notification on push

on:
  push:
    branches:
    - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DISCORD_USERNAME: mavrosjs
        DISCORD_AVATAR: https://raw.githubusercontent.com/mavrojs/mavro/6caa939c0475efbb65ecdba02f4e27db18b3c0a6/.github/resources/mavro-icon.svg
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new activity in mavrojs/mavro.'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      uses: Ilshidur/action-discord@master