name: CI

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

permissions:
  contents: write  # Grant write permissions for the repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Build the project
        run: npm run build

      - name: Run release
        run: npm run release

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit after build and release" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main  # Change this to your target branch
