name: CI

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Build the project
        run: npm run build

      - name: Run release
        run: npm run release

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit after build and release" || echo "No changes to commit"

      - name: Push changes
        run: git push origin release  # Ensure this matches your branch setup

      # Step 9: Publish to npm
      - name: Publish to npm
        if: success()  # This ensures the npm publish step runs only if previous steps were successful
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
