name: Release on [push, merge] to release branch

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Set Git user
        run: |
          git config --global user.email "otmannj56@gmail.com"
          git config --global user.name "iietmoon"

      # Build the project
      - name: Build the project
        run: npm run build

      # Run standard-version to bump version and generate changelog
      - name: Run standard-version
        run: npm run release

      # Use Add & Commit action to commit with GitHub Actions bot and sign commits
      - name: Add & Commit version bump
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "chore(release): version bump"
          signoff: true  # This adds the Signed-off-by line
        continue-on-error: true  # Avoid failing if there's nothing to commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the tags after committing
      - name: Push tags
        run: git push --follow-tags origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish to npm
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
