name: Release on [push, merge] to release branch

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set Git user
        run: |
          git config --global user.email "otmannj56@gmail.com"
          git config --global user.name "iietmoon"

      - name: Run standard-version
        run: npm run release

      - name: Commit version bump
        run: |
          git add .
          git commit -m "chore(release): version bump"
          git push --follow-tags origin release

      - name: 🧪 Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
